### Get all TodoItems
GET https://localhost:8443/dmit2015-1221-backend/restapi/TodoItems

### Get a single TodoItem with an id of 1
GET https://localhost:8443/dmit2015-1221-backend/restapi/TodoItems/1

### POST a new TodoItem with valid data
POST https://localhost:8443/dmit2015-1221-backend/restapi/TodoItems
Content-Type: application/json

{
  "name": "Start DMIT2015 Assignment 6",
  "complete": false
}

### Post a new TodoItem with invalid data
POST https://localhost:8443/dmit2015-1221-backend/restapi/TodoItems
Content-Type: application/json

{
  "name": "     ",
  "complete": false
}

### Get a single TodoItem with an id of 4
GET https://localhost:8443/dmit2015-1221-backend/restapi/TodoItems/4

### Update TodoItem with an id of 4 with valid data
PUT https://localhost:8443/dmit2015-1221-backend/restapi/TodoItems/4
Content-Type: application/json

{
  "id": 4,
  "name": "Commit and push DMIT2015 Assignment 6",
  "complete": true,
  "version": 0
}

### Delete an TodoItem with an id of 2
DELETE https://localhost:8443/dmit2015-1221-backend/restapi/TodoItems/2

### Delete an TodoItem with an id of 4
DELETE https://localhost:8443/dmit2015-1221-backend/restapi/TodoItems/4